import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Plus_Jakarta_Sans } from "next/font/google";
import Navbar from "@/components/layout/Navbar"
import Footer from "@/components/layout/Footer"
// import type { ReactNode } from "react"
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'], // Or other subsets if needed
  weight: ['400', '700'],
  variable: '--font-jakarta-sans', 
});

export const metadata: Metadata = {
  title: "Wave Creative",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en" className={jakartaSans.variable}>
      <body className="font-sans min-h-screen flex flex-col bg-background text-foreground dark:bg-gray-950 scheme-light dark:scheme-dark">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
    );
}
